#!/bin/bash

# Prompt for user's name
read -p "What's your name:>_ " User
#echo "Welcome, $User!"
echo "🚀 Welcome, $User! Ready to build something awesome?"
# Get the first line of the changelog
firstline=$(head -n 1 source/changelog.md)
echo "$firstline"

# Split the first line into an array
read -a splitfirstline <<< "$firstline"
version=${splitfirstline[1]}
echo "You are building version $version"

# Prompt to continue
read -p "Do you want to continue? (Enter '1' for yes, or '0' for no): " versioncontinue

if [ "$versioncontinue" = 1 ]; then
    # proceed
    echo "Ok, proceeding with the build."
    for filename in source/*; do
        # Check if the file is secretinfo.md
        if [ "$(basename "$filename")" == "secretinfo.md" ]; then
            echo "Not copying $filename"
        else
            if [ ! -d build ]; then
              mkdir build
            fi  
            echo "Copying $filename to build/"
            cp -v "$filename" build/
        fi
    done

    # List contents of the build directory
    cd build/ || exit
    #echo "Build version $version contains:"
    echo "Build directory now contains the following files for version $version:"
    ls
    cd .. || exit
elif [ "$versioncontinue" = "0" ]; then
    echo "Please come back when you are ready."
    # Copy files excluding secretinfo.md
    #Loop through each file in the source directory and copy it to build, except secretinfo.md
else
    echo "Invalid input. Please enter '1' or '0'."
    exit 1

fi
