#!/usr/bin/env bash


# Colors

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # No Color

# Function to display help message.
show_help() {
    cat << EOF
NAME: $(basename "$0") - A utility script.

SYNOPSIS: $(basename "$0") COMMAND [OPTIONS]

DESCRIPTION:A simple script that provides different functionalities:
        - Extract user-defined aliases from the system.
        - Recover stored passwords (not yet implemented).

COMMANDS:
    ea: Extract aliases by fetching and executing the extract_aliases.sh script.
        -q: Run in quiet mode (suppress non-essential output).
        -o <file>: Write extracted aliases to the specified output file.

    rp: Recover passwords (currently not implemented).

    exit: Exit the script.

OPTIONS:
    -h, --help
        Display this help message and exit.

EXAMPLES:
    Direct mode:
        $(basename "$0") ea
        $(basename "$0") ea -q -o output.md
        $(basename "$0") rp
    Interactive mode:
        $(basename "$0")

AUTHOR: Gabriel D. Vincent
EOF
}

# Function to extract aliases
extract_aliases() {
    echo "You chose to extract aliases..."
    tmp=$(mktemp)
    curl -s -o "$tmp" https://raw.githubusercontent.com/Gabriel-Dakinah-Vincent/Bash-exercises/main/extract-aliases/src/extract_aliases.sh
    bash "$tmp" "$@"
    rm "$tmp"
    #curl -s https://raw.githubusercontent.com/Gabriel-Dakinah-Vincent/Bash-exercises/main/extract-aliases/src/extract_aliases.sh | bash -s -- "$@"
}

# Function to recover passwords (not implemented yet)
recover_passwords() {
    echo "You chose to recover passwords."
    echo "This functionality is not yet implemented."
    return 1
}

# Check if an argument is passed
case "$1" in
    ea)
        shift
        extract_aliases "$@"
        exit 0
        ;;
    rp)
        recover_passwords
        exit 0
        ;;
   
    -h|--help)
        show_help
        exit 0
        ;;

    exit)
        echo "Exiting the script. Goodbye!"
        exit 0
        ;;
esac

finished=0

# Detect non-interactive shell without arguments
if ! [ -t 0 ]; then
    echo -e "${RED}Error:${NC} Non-interactive shell detected. Please provide an argument."
    exit 1
fi

while [ $finished -ne 1 ]; do
    echo "What do you want to test?"
    echo -e "1. Extract Aliases: ${GREEN}ea${NC}"
    echo -e "2. Recover Passwords: ${GREEN}rp${NC}"
    echo -e "3. Exit: ${CYAN}exit${NC}"
    prompt="Please enter your choice (${GREEN}ea${NC}/${GREEN}rp${NC}/${CYAN}exit${NC}): "
    read -p "$(echo -e "$prompt")" choice

    case $choice in
        ea)
            extract_aliases "$@"
            ;;
        rp)
            recover_passwords
            ;;

        exit)
            finished=1
            echo -e "${CYAN}Exiting the script. Goodbye!${NC}"
            ;;
        *)
            echo -e "${RED}Error:${NC} Invalid choice. Please enter '${GREEN}ea${NC}', '${GREEN}rp${NC}', or '${CYAN}exit${NC}'."
            ;;
    esac
done

echo -e "${GREEN}Thank you for using the script. Goodbye!${NC}"