#
# Module manifest for module 'Audit'
#
# Generated by: Gabriel Dakinah Vincent
# Generated on: 11/6/2025
#

@{
    RootModule        = 'Audit.psm1'
    ModuleVersion     = '2.0.0'
    GUID              = '11b9b12a-2371-4343-9bb9-f54335619065'
    Author            = 'Gabriel Dakinah Vincent'
    CompanyName       = ''
    Copyright         = '(c) 2025 Gabriel Dakinah Vincent. All rights reserved.'
    Description       = 'A comprehensive PowerShell module for Windows security auditing including user accounts, persistence mechanisms, and threat detection and more.'

    PowerShellVersion = '5.1'
    CompatiblePSEditions = @('Desktop', 'Core')

    # Updated + Future-proof list of exported functions
    FunctionsToExport = @(
        'Get-Audit',
        'Get-LocalAdmins',
        'Get-LastLogon',
        'Get-Sessions',
        'Get-DefensiveServices',
        'Get-EDRSolutions',
        'Get-PasswordPolicy',
        'Get-RegistryPersistence',
        'Get-ScheduledTaskAbuse',
        'Get-ServiceHijacking',
        'Get-DLLSideloading',
        'Get-WMIEventSubscription',
        'Get-ProfilePersistence',
        'Show-AuditHelp',
        'Invoke-Audit'
    )

    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @()

    PrivateData = @{
        PSData = @{
            ProjectUri   = 'https://github.com/Gabriel-Dakinah-Vincent/Scriptmanem'
            ReleaseNotes = 'Version 2.0.0: Added comprehensive Windows persistence detection, risk scoring, privilege validation, and rate limiting capabilities.'
        }
    }
}